import React, { useState } from 'react';
import PptxGenJS from 'pptxgenjs';
import * as Icons from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import AgenticPPTGenerator from './AgenticPPTGenerator';
import { getAICompletion } from '../../utils/aiService';

const PresentationGenerator = ({ onBack, initialType = 'presentation' }) => {
    const [step, setStep] = useState(2); // Start at input
    const [generationMode, setGenerationMode] = useState('quick'); // 'quick' | 'agentic'
    const [formData, setFormData] = useState({
        topic: '',
        audience: 'University Students',
        tone: 'Academic',
        slideCount: 5,
        details: '',
        customInstructions: '',
        theme: 'modern',
        descriptionLength: 'short',
        includeDiagrams: true
    });
    const [loading, setLoading] = useState(false);
    const [generatedContent, setGeneratedContent] = useState(null);
    const [error, setError] = useState(null);

    const themesList = [
        { id: 'modern', name: 'Modern Dark', color: '#1e1b4b' },
        { id: 'minimal', name: 'Minimal Light', color: '#f8fafc' },
        { id: 'nature', name: 'Nature', color: '#064e3b' },
        { id: 'corporate', name: 'Corporate', color: '#1e3a8a' },
    ];

    const handleGenerate = async () => {
        setLoading(true);
        setError(null);
        try {
            const prompt = `Generate a high-quality ${formData.slideCount}-slide presentation deck on "${formData.topic}". 
 Audience: ${formData.audience}. Tone: ${formData.tone}.
 Theme Preference: ${formData.theme}.
 OUTPUT FORMAT: JSON ONLY.
 
 Structure:
 {
   "title": "Main Presentation Title",
   "subtitle": "Informative subtitle",
   "slides": [
     { 
       "title": "Slide Title", 
       "layout": "title_content" | "two_column" | "quote",
       "bullets": ["Point 1", "Point 2"], 
       "extraContent": "Additional context or quote",
       "iconHint": "lucide icon name (e.g., Code, Cpu, Book, Zap, Activity, Shield)"
     }
   ]
 }
 
 LAYOUT RULES:
 - "quote": extraContent is the main quote.
 - "two_column": bullets are split evenly.
 - "title_content": standard title and bullet list.
 
 ALWAYS prioritize simplicity, useful content, and maximum readability.`;

            let aiText = await getAICompletion(
                [
                    { "role": "system", "content": "You are a helpful academic assistant. You generate structured content in strict JSON format. IMPORTANT: Only return the JSON object, do not include markdown code blocks or any other text." },
                    { "role": "user", "content": prompt }
                ],
                { jsonMode: true }
            );

            aiText = aiText.replace(/```json/g, '').replace(/```/g, '').trim();
            const parsedContent = JSON.parse(aiText);
            setGeneratedContent(parsedContent);
            setStep(3);
        } catch (err) {
            console.error(err);
            setError("Failed to generate content. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const downloadPPT = () => {
        if (!generatedContent) return;
        const pres = new PptxGenJS();

        const themes = {
            simple: { bg: 'FFFFFF', primary: '3182CE', text: '1A202C' },
            corporate: { bg: 'F7FAFC', primary: '2C5282', text: '2D3748' },
            academic: { bg: 'FFFFFF', primary: '4A5568', text: '1A202C' },
            modern: { bg: 'FFFFFF', primary: '805AD5', text: '2D3748' },
            minimal: { bg: 'f8fafc', primary: '0f172a', text: '334155' },
            nature: { bg: 'f0fdf4', primary: '15803d', text: '14532d' }
        };
        const theme = themes[formData.theme] || themes[generatedContent.theme] || themes.simple;

        pres.defineSlideMaster({
            title: 'MASTER_SLIDE',
            background: { color: theme.bg },
            footer: { x: 1, y: 7.2, h: 0.3, text: 'Generated by IES Notes AI', fontSize: 10, color: '718096' },
            margin: [0.5, 0.5, 0.5, 0.5]
        });

        let slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });
        slide.addText(generatedContent.title, {
            x: 0.5, y: 2.5, w: 9.0, fontSize: 44, align: 'center', bold: true, color: theme.primary,
            fontFace: 'Arial'
        });
        if (generatedContent.subtitle) {
            slide.addText(generatedContent.subtitle, {
                x: 0.5, y: 3.5, w: 9.0, fontSize: 24, align: 'center', color: '4A5568',
                italic: true
            });
        }

        generatedContent.slides.forEach(s => {
            slide = pres.addSlide({ masterName: 'MASTER_SLIDE' });
            slide.addShape(pres.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.05, fill: { color: theme.primary } });
            slide.addText(s.title, { x: 0.5, y: 0.5, w: '90%', fontSize: 32, bold: true, color: theme.primary });

            if (s.layout === 'two_column') {
                const mid = Math.ceil(s.bullets.length / 2);
                slide.addText(s.bullets.slice(0, mid).map(b => ({ text: b, options: { bullet: true } })), { x: 0.5, y: 1.5, w: '4.5', h: '5.0', fontSize: 18, color: theme.text });
                slide.addText(s.bullets.slice(mid).map(b => ({ text: b, options: { bullet: true } })), { x: 5.0, y: 1.5, w: '4.5', h: '5.0', fontSize: 18, color: theme.text });
            } else if (s.layout === 'quote') {
                slide.addShape(pres.ShapeType.rect, { x: 1, y: 2, w: 8, h: 3, fill: { color: 'F7FAFC' }, line: { color: theme.primary, width: 2 } });
                slide.addText(s.extraContent || s.bullets[0], {
                    x: 1.5, y: 2.5, w: 7.0, fontSize: 28, align: 'center', color: theme.primary, italic: true
                });
            } else {
                slide.addText(s.bullets.map(b => ({ text: b, options: { bullet: true } })), { x: 0.5, y: 1.5, w: 9.0, h: '5.0', fontSize: 18, color: theme.text });
            }
        });

        pres.writeFile({ fileName: `${formData.topic.replace(/\s+/g, '_')}_Presentation.pptx` });
    };

    const containerVariants = {
        hidden: { opacity: 0, scale: 0.95 },
        visible: { opacity: 1, scale: 1, transition: { duration: 0.3 } },
        exit: { opacity: 0, scale: 0.95, transition: { duration: 0.2 } }
    };

    return (
        <AnimatePresence mode="wait">
            <motion.div
                key={step}
                variants={containerVariants}
                initial="hidden"
                animate="visible"
                exit="exit"
                className="d-flex flex-column h-100 w-100 min-vh-100 bg-light"
            >
                {/* Header */}
                <div className="p-4 d-flex align-items-center mb-4 bg-white shadow-sm sticky-top" style={{ zIndex: 100 }}>
                    <button
                        onClick={onBack}
                        className="btn btn-light rounded-circle p-2 shadow-sm d-flex align-items-center justify-content-center me-3 border"
                        style={{ width: 44, height: 44 }}
                    >
                        <Icons.ArrowLeft size={20} className="text-muted" />
                    </button>
                    <div>
                        <h2 className="fw-bold m-0 d-flex align-items-center gap-2 text-dark">
                            <Icons.Presentation size={24} className="text-primary" />
                            Presentation Generator
                        </h2>
                        <p className="text-muted m-0 small">Create slides instantly</p>
                    </div>
                </div>

                {/* Body */}
                <div className="flex-grow-1 overflow-auto px-4 pb-5 custom-scrollbar container" style={{ maxWidth: '800px' }}>
                    {step === 2 && (
                        <div className="clay-card p-4 mb-4 bg-white shadow-sm rounded-4">
                            <h3 className="fw-bold mb-4 text-dark">Customize your Presentation</h3>

                            <div className="mb-4">
                                <label className="form-label fw-bold text-muted small text-uppercase">Topic</label>
                                <input
                                    type="text"
                                    className="form-control border-0 bg-light p-3 rounded-3"
                                    placeholder="e.g. Artificial Intelligence in 2025"
                                    value={formData.topic}
                                    onChange={e => setFormData({ ...formData, topic: e.target.value })}
                                />
                            </div>

                            <div className="mb-4">
                                <label className="form-label fw-bold text-muted small text-uppercase">Custom Instructions (Optional)</label>
                                <textarea
                                    className="form-control border-0 bg-light p-3 rounded-3"
                                    rows="2"
                                    placeholder="e.g. Focus on medical applications..."
                                    value={formData.customInstructions}
                                    onChange={e => setFormData({ ...formData, customInstructions: e.target.value })}
                                />
                            </div>

                            <div className="mb-4">
                                <label className="form-label fw-bold text-muted small text-uppercase">Number of Slides</label>
                                <input
                                    type="number"
                                    className="form-control border-0 bg-light p-3 rounded-3"
                                    min="3" max="15"
                                    value={formData.slideCount}
                                    onChange={e => setFormData({ ...formData, slideCount: e.target.value })}
                                />
                            </div>

                            <div className="row g-4 mb-4">
                                <div className="col-md-6">
                                    <label className="form-label fw-bold text-muted small text-uppercase">Target Audience</label>
                                    <select className="form-select border-0 bg-light p-3 rounded-3" value={formData.audience} onChange={e => setFormData({ ...formData, audience: e.target.value })}>
                                        <option>High School Students</option>
                                        <option>University Students</option>
                                        <option>Professionals</option>
                                        <option>General Public</option>
                                    </select>
                                </div>
                                <div className="col-md-6">
                                    <label className="form-label fw-bold text-muted small text-uppercase">Tone</label>
                                    <select className="form-select border-0 bg-light p-3 rounded-3" value={formData.tone} onChange={e => setFormData({ ...formData, tone: e.target.value })}>
                                        <option>Academic</option>
                                        <option>Casual</option>
                                        <option>Professional</option>
                                        <option>Creative</option>
                                    </select>
                                </div>
                            </div>

                            <div className="row g-4 mb-4">
                                <div className="col-md-6">
                                    <label className="form-label fw-bold text-muted small text-uppercase">Description Length</label>
                                    <select
                                        className="form-select border-0 bg-light p-3 rounded-3"
                                        value={formData.descriptionLength}
                                        onChange={e => setFormData({ ...formData, descriptionLength: e.target.value })}
                                    >
                                        <option value="short">Short (Concise)</option>
                                        <option value="long">Long (Detailed)</option>
                                    </select>
                                </div>
                                <div className="col-md-6">
                                    <label className="form-label fw-bold text-muted small text-uppercase">Diagrams</label>
                                    <div className="d-flex align-items-center gap-3 pt-2">
                                        <div className="form-check form-switch cursor-pointer">
                                            <input
                                                className="form-check-input"
                                                type="checkbox"
                                                role="switch"
                                                id="diagramsToggle"
                                                checked={formData.includeDiagrams}
                                                onChange={e => setFormData({ ...formData, includeDiagrams: e.target.checked })}
                                            />
                                            <label className="form-check-label" htmlFor="diagramsToggle">Include Mermaid Diagrams</label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="mb-4">
                                <label className="form-label fw-bold text-muted small text-uppercase">Preset Theme</label>
                                <div className="d-flex gap-2 overflow-auto pb-2 custom-scrollbar">
                                    {themesList.map(t => (
                                        <div
                                            key={t.id}
                                            onClick={() => setFormData({ ...formData, theme: t.id })}
                                            className={`rounded p-3 cursor-pointer d-flex flex-column align-items-center justify-content-center border transition-all ${formData.theme === t.id ? 'ring-2 ring-primary shadow-md' : 'opacity-75 hover-opacity-100'}`}
                                            style={{
                                                minWidth: '100px',
                                                background: t.color,
                                                color: t.id === 'minimal' ? '#333' : 'white',
                                                border: formData.theme === t.id ? '2px solid var(--primary-accent)' : '1px solid transparent',
                                                borderRadius: '16px'
                                            }}
                                        >
                                            <div className="fw-bold small">{t.name}</div>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            <div className="mb-4">
                                <label className="form-label fw-bold text-muted small text-uppercase">Generation Mode</label>
                                <div className="d-flex gap-3">
                                    <div
                                        className={`card p-3 cursor-pointer flex-grow-1 border-0 ${generationMode === 'quick' ? 'ring-2 ring-primary shadow-sm' : ''}`}
                                        style={{
                                            background: generationMode === 'quick' ? '#eff6ff' : '#f8fafc',
                                            transform: generationMode === 'quick' ? 'translateY(-2px)' : 'none',
                                            transition: 'all 0.2s'
                                        }}
                                        onClick={() => setGenerationMode('quick')}
                                    >
                                        <div className="fw-bold d-flex align-items-center justify-content-center gap-2 text-primary"><Icons.Zap size={18} className="text-warning" /> Quick PPTX</div>
                                        <div className="small text-muted text-center mt-1">Direct Download</div>
                                    </div>
                                    <div
                                        className={`card p-3 cursor-pointer flex-grow-1 border-0 ${generationMode === 'agentic' ? 'ring-2 ring-primary shadow-sm' : ''}`}
                                        style={{
                                            background: generationMode === 'agentic' ? '#eff6ff' : '#f8fafc',
                                            transform: generationMode === 'agentic' ? 'translateY(-2px)' : 'none',
                                            transition: 'all 0.2s'
                                        }}
                                        onClick={() => setGenerationMode('agentic')}
                                    >
                                        <div className="fw-bold d-flex align-items-center justify-content-center gap-2 text-primary"><Icons.Bot size={18} className="text-info" /> Agentic Web Slides</div>
                                        <div className="small text-muted text-center mt-1">View & Edit Online</div>
                                    </div>
                                </div>
                            </div>

                            <button
                                className="btn btn-primary w-100 py-3 fw-bold d-flex align-items-center justify-content-center gap-2 fs-5 shadow-lg mt-2 rounded-pill"
                                onClick={() => {
                                    if (generationMode === 'agentic') setStep(4);
                                    else handleGenerate();
                                }}
                                disabled={!formData.topic || loading}
                            >
                                {loading ? <span className="spinner-border spinner-border-sm"></span> : <>Start Generation <Icons.Sparkles size={20} /></>}
                            </button>
                        </div>
                    )}

                    {step === 4 && (
                        <AgenticPPTGenerator
                            topic={formData.topic}
                            details={formData.details}
                            slideCount={formData.slideCount}
                            customInstructions={formData.customInstructions}
                            theme={formData.theme}
                            descriptionLength={formData.descriptionLength}
                            includeDiagrams={formData.includeDiagrams}
                            onBack={() => setStep(2)}
                        />
                    )}

                    {step === 3 && generatedContent && (
                        <div className="container h-100 flex-column d-flex">
                            <div className="text-center mb-4">
                                <h2 className="fw-bold text-dark">{generatedContent.title}</h2>
                            </div>

                            <div className="flex-grow-1 overflow-auto p-4 mb-4 rounded-4 border bg-white custom-scrollbar shadow-sm">
                                <div className="d-flex flex-column gap-4 align-items-center">
                                    {generatedContent.slides.map((slide, idx) => (
                                        <div key={idx} className="bg-light shadow-sm p-5 border rounded-3 w-100" style={{ maxWidth: '800px', aspectRatio: '16/9' }}>
                                            <h3 className="fw-bold mb-4 text-primary border-bottom pb-2">{slide.title}</h3>
                                            <ul className="fs-5">
                                                {slide.bullets.map((b, i) => <li key={i} className="mb-2">{b}</li>)}
                                            </ul>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            <div className="d-flex gap-3 justify-content-center pb-4">
                                <button className="btn btn-secondary rounded-pill px-4" onClick={() => setStep(2)}>Edit</button>
                                <button className="btn btn-primary rounded-pill px-5 fw-bold shadow-lg" onClick={downloadPPT}>
                                    <Icons.Download size={20} className="me-2" /> Download PPTX
                                </button>
                            </div>
                        </div>
                    )}
                </div>
            </motion.div>
        </AnimatePresence>
    );
};

export default PresentationGenerator;
