import React, { useState } from 'react';
import PptxGenJS from 'pptxgenjs';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Presentation, FileText, CheckSquare, Download, Sparkles, ChevronRight, ArrowLeft } from 'lucide-react';

const ContentGenerator = ({ onBack }) => {
    const [step, setStep] = useState(1); // 1: Select Type, 2: Input Details, 3: Generating/Preview
    const [contentType, setContentType] = useState(null); // 'presentation', 'report', 'assignment'
    const [formData, setFormData] = useState({
        topic: '',
        audience: 'University Students',
        tone: 'Academic',
        slideCount: 5,
        details: ''
    });
    const [loading, setLoading] = useState(false);
    const [generatedContent, setGeneratedContent] = useState(null);
    const [error, setError] = useState(null);

    const handleTypeSelect = (type) => {
        setContentType(type);
        setStep(2);
    };

    const handleGenerate = async () => {
        setLoading(true);
        setError(null);

        try {
            // PROMPT ENGINEERING FOR AURORA-ALPHA
            let prompt = "";
            if (contentType === 'presentation') {
                prompt = `Generate a ${formData.slideCount}-slide presentation outline on "${formData.topic}". 
 Audience: ${formData.audience}. Tone: ${formData.tone}.
 OUTPUT FORMAT: JSON ONLY.
 Structure:
 {
   "title": "Presentation Title",
   "slides": [
     { "title": "Slide Title", "bullets": ["Point 1", "Point 2", "Point 3"] }
   ]
 }`;
            } else if (contentType === 'report') {
                prompt = `Generate a detailed academic report on "${formData.topic}". 
 Audience: ${formData.audience}. Tone: ${formData.tone}.
 OUTPUT FORMAT: JSON ONLY.
 Structure:
 {
   "title": "Report Title",
   "sections": [
     { "heading": "Section Heading", "content": "Paragraph content..." }
   ]
 }`;
            } else if (contentType === 'assignment') {
                prompt = `Generate an assignment on "${formData.topic}". 
 Level: ${formData.audience}.
 OUTPUT FORMAT: JSON ONLY.
 Structure:
 {
   "title": "Assignment Title",
   "questions": [
     { "question": "Question text?", "marks": "5", "answerKey": "Brief answer" }
   ]
 }`;
            }

            const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Authorization": `Bearer ${import.meta.env.VITE_OPENROUTER_API_KEY}`,
                    "Content-Type": "application/json",
                    "HTTP-Referer": window.location.origin,
                    "X-Title": "IES Notes AI"
                },
                body: JSON.stringify({
                    "model": "google/gemini-2.0-flash-001",
                    "messages": [
                        { "role": "system", "content": "You are a helpful academic assistant. You generate structured content in strict JSON format. IMPORTANT: Only return the JSON object, do not include markdown code blocks or any other text." },
                        { "role": "user", "content": prompt }
                    ],
                    "response_format": { "type": "json_object" }
                })
            });

            if (!response.ok) throw new Error("AI Generation Failed");

            const data = await response.json();
            let aiText = data.choices[0].message.content;

            // Clean markdown code blocks if present
            aiText = aiText.replace(/```json/g, '').replace(/```/g, '').trim();

            const parsedContent = JSON.parse(aiText);
            setGeneratedContent(parsedContent);
            setStep(3);

        } catch (err) {
            console.error(err);
            setError("Failed to generate content. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const downloadPPT = () => {
        if (!generatedContent) return;
        const pres = new PptxGenJS();

        // Title Slide
        let slide = pres.addSlide();
        slide.addText(generatedContent.title, { x: 1, y: 1, w: '80%', fontSize: 36, align: 'center', bold: true, color: '363636' });
        slide.addText(`Generated by IES Notes AI`, { x: 1, y: 5, w: '80%', fontSize: 18, align: 'center', color: '808080' });

        // Content Slides
        generatedContent.slides.forEach(s => {
            slide = pres.addSlide();
            slide.addText(s.title, { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true, color: '363636' });
            slide.addText(s.bullets.map(b => ({ text: b, options: { bullet: true } })), { x: 0.5, y: 1.5, w: '90%', h: '70%', fontSize: 18, color: '505050' });
        });

        pres.writeFile({ fileName: `${formData.topic.replace(/\s+/g, '_')}_Presentation.pptx` });
    };

    const downloadPDF = () => {
        if (!generatedContent) return;
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        let y = 20;

        // Helper for text wrapping
        const addText = (text, size, isBold = false) => {
            doc.setFontSize(size);
            doc.setFont("helvetica", isBold ? "bold" : "normal");
            const splitText = doc.splitTextToSize(text, pageWidth - 40);
            doc.text(splitText, 20, y);
            y += splitText.length * (size / 2) + 5; // simplified line height
            if (y > 280) { doc.addPage(); y = 20; }
        };

        addText(generatedContent.title, 22, true);
        y += 10;

        if (contentType === 'report') {
            generatedContent.sections.forEach(section => {
                addText(section.heading, 16, true);
                addText(section.content, 12, false);
                y += 5;
            });
        } else if (contentType === 'assignment') {
            generatedContent.questions.forEach((q, i) => {
                addText(`Q${i + 1}: ${q.question} (${q.marks} marks)`, 12, true);
                addText(`Answer Key: ${q.answerKey}`, 10, false);
                y += 5;
            });
        }

        doc.save(`${formData.topic.replace(/\s+/g, '_')}_${contentType}.pdf`);
    };

    return (
        <div className="d-flex flex-column h-100 bg-white rounded-3 shadow-sm border overflow-hidden">
            {/* Header */}
            <div className="p-3 border-bottom d-flex align-items-center bg-light">
                <button onClick={onBack} className="btn btn-sm btn-outline-secondary me-2 rounded-circle w-30 h-30 d-flex align-items-center justify-content-center">
                    <ArrowLeft size={18} />
                </button>
                <h5 className="m-0 fw-bold d-flex align-items-center gap-2">
                    <Sparkles size={18} className="text-primary" />
                    AI Content Generator
                </h5>
            </div>

            {/* Body */}
            <div className="flex-grow-1 overflow-auto p-4">
                {step === 1 && (
                    <div className="row g-3">
                        <div className="col-12 text-center mb-4">
                            <h3 className="fw-bold text-dark">What would you like to create?</h3>
                            <p className="text-muted">Select a tool to start generating content.</p>
                        </div>
                        {[
                            { id: 'presentation', icon: Presentation, title: "Presentation", desc: "Generate PPT slides with structured outlines." },
                            { id: 'report', icon: FileText, title: "Report", desc: "Create detailed academic reports formatted as PDF." },
                            { id: 'assignment', icon: CheckSquare, title: "Assignment", desc: "Generate questions, quizzes, and marking schemes." }
                        ].map(tool => (
                            <div key={tool.id} className="col-md-4">
                                <button
                                    onClick={() => handleTypeSelect(tool.id)}
                                    className="btn btn-outline-light text-dark border p-4 w-100 h-100 d-flex flex-column align-items-center gap-3 shadow-sm hover-shadow"
                                    style={{ transition: 'all 0.2s' }}
                                >
                                    <div className="bg-primary bg-opacity-10 p-3 rounded-circle text-primary">
                                        <tool.icon size={32} />
                                    </div>
                                    <div className="text-center">
                                        <h5 className="fw-bold mb-1">{tool.title}</h5>
                                        <p className="small text-muted mb-0">{tool.desc}</p>
                                    </div>
                                </button>
                            </div>
                        ))}
                    </div>
                )}

                {step === 2 && (
                    <div className="max-w-600 mx-auto">
                        <h4 className="fw-bold mb-4">Customize your {contentType}</h4>
                        <div className="mb-3">
                            <label className="form-label fw-bold">Topic</label>
                            <input
                                type="text"
                                className="form-control"
                                placeholder="e.g. Artificial Intelligence in 2025"
                                value={formData.topic}
                                onChange={e => setFormData({ ...formData, topic: e.target.value })}
                            />
                        </div>

                        <div className="row g-3 mb-3">
                            <div className="col-md-6">
                                <label className="form-label fw-bold">Target Audience</label>
                                <select className="form-select" value={formData.audience} onChange={e => setFormData({ ...formData, audience: e.target.value })}>
                                    <option>High School Students</option>
                                    <option>University Students</option>
                                    <option>Professionals</option>
                                    <option>General Public</option>
                                </select>
                            </div>
                            <div className="col-md-6">
                                <label className="form-label fw-bold">Tone</label>
                                <select className="form-select" value={formData.tone} onChange={e => setFormData({ ...formData, tone: e.target.value })}>
                                    <option>Academic</option>
                                    <option>Casual</option>
                                    <option>Professional</option>
                                    <option>Creative</option>
                                </select>
                            </div>
                        </div>

                        {contentType === 'presentation' && (
                            <div className="mb-3">
                                <label className="form-label fw-bold">Number of Slides</label>
                                <input
                                    type="number"
                                    className="form-control"
                                    min="3" max="15"
                                    value={formData.slideCount}
                                    onChange={e => setFormData({ ...formData, slideCount: e.target.value })}
                                />
                            </div>
                        )}

                        <div className="mb-4">
                            <label className="form-label fw-bold">Additional Details</label>
                            <textarea
                                className="form-control"
                                rows="3"
                                placeholder="Any specific points to include?"
                                value={formData.details}
                                onChange={e => setFormData({ ...formData, details: e.target.value })}
                            ></textarea>
                        </div>

                        <div className="d-flex gap-2">
                            <button className="btn btn-secondary flex-grow-1" onClick={() => setStep(1)}>Back</button>
                            <button
                                className="btn btn-primary flex-grow-1 d-flex align-items-center justify-content-center gap-2"
                                onClick={handleGenerate}
                                disabled={!formData.topic || loading}
                            >
                                {loading ? (
                                    <>
                                        <span className="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        Generate <Sparkles size={18} />
                                    </>
                                )}
                            </button>
                        </div>

                        {error && <div className="alert alert-danger mt-3">{error}</div>}
                    </div>
                )}

                {step === 3 && generatedContent && (
                    <div className="h-100 d-flex flex-column">
                        <div className="text-center mb-4">
                            <div className="d-inline-flex align-items-center gap-2 bg-success bg-opacity-10 text-success px-3 py-1 rounded-pill mb-2">
                                <CheckSquare size={16} /> Generated Successfully
                            </div>
                            <h3 className="fw-bold">{generatedContent.title}</h3>
                        </div>

                        <div className="flex-grow-1 overflow-auto bg-light p-4 rounded border mb-4">
                            {/* Preview Logic */}
                            {contentType === 'presentation' && (
                                <div className="d-flex flex-column gap-4">
                                    {generatedContent.slides.map((slide, idx) => (
                                        <div key={idx} className="bg-white p-4 shadow-sm rounded border">
                                            <h5 className="fw-bold text-primary mb-3">Slide {idx + 1}: {slide.title}</h5>
                                            <ul className="mb-0">
                                                {slide.bullets.map((b, i) => <li key={i}>{b}</li>)}
                                            </ul>
                                        </div>
                                    ))}
                                </div>
                            )}

                            {contentType === 'report' && (
                                <div className="bg-white p-5 shadow-sm rounded border max-w-800 mx-auto">
                                    <h2 className="text-center fw-bold mb-5">{generatedContent.title}</h2>
                                    {generatedContent.sections.map((section, idx) => (
                                        <div key={idx} className="mb-4">
                                            <h4 className="fw-bold border-bottom pb-2 mb-3">{section.heading}</h4>
                                            <p className="text-justify">{section.content}</p>
                                        </div>
                                    ))}
                                </div>
                            )}

                            {contentType === 'assignment' && (
                                <div className="bg-white p-5 shadow-sm rounded border max-w-800 mx-auto">
                                    <h2 className="text-center fw-bold mb-5">{generatedContent.title}</h2>
                                    {generatedContent.questions.map((q, idx) => (
                                        <div key={idx} className="mb-4 p-3 border rounded bg-light">
                                            <div className="d-flex justify-content-between mb-2">
                                                <span className="fw-bold">Q{idx + 1}: {q.question}</span>
                                                <span className="badge bg-secondary">{q.marks} Marks</span>
                                            </div>
                                            <p className="text-muted small mb-0">Answer Key: {q.answerKey}</p>
                                        </div>
                                    ))}
                                </div>
                            )}
                        </div>

                        <div className="d-flex gap-2 justify-content-center">
                            <button className="btn btn-outline-secondary" onClick={() => setStep(2)}>Back to Edit</button>
                            <button
                                className="btn btn-primary d-flex align-items-center gap-2"
                                onClick={contentType === 'presentation' ? downloadPPT : downloadPDF}
                            >
                                <Download size={18} />
                                Download {contentType === 'presentation' ? 'PPTX' : 'PDF'}
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default ContentGenerator;
