import pptxgen from "pptxgenjs";

export const generateNativePPT = (theme, slideDataArray, filename = "HOPE_Presentation") => {
    let pptx = new pptxgen();

    // 1. Define the Global Theme Colors
    const isDark = theme === 'dark';
    const bgColor = isDark ? '1E293B' : (theme === 'corporate' ? 'F8FAFC' : 'FFFFFF');
    // For standard sliding text (opposite of bg)
    const textColor = isDark ? 'F1F5F9' : '1E293B';
    // Pop colors for shapes/accents
    const accentColor = theme === 'corporate' ? '2563EB' : '8B5CF6';

    // 2. Define the Global Master Slide Branding
    pptx.defineSlideMaster({
        title: "HOPE_MASTER",
        background: { color: bgColor },
        objects: [
            // Top corporate accent bar
            { rect: { x: 0, y: 0, w: "100%", h: 0.15, fill: { color: accentColor } } },
            // Subtle footer branding
            { text: { text: "Generated by HOPE Studio", options: { x: 0.4, y: 5.2, fontSize: 10, color: "94A3B8", fontFace: "Helvetica" } } },
            // Slide Numbers
            { slideNumber: { x: 9.3, y: 5.2, fontSize: 10, color: "94A3B8", fontFace: "Helvetica" } }
        ]
    });

    slideDataArray.forEach((data) => {
        // Apply the master template to every slide
        let slide = pptx.addSlide({ masterName: "HOPE_MASTER" });

        switch (data.layout) {
            case "TITLE_SLIDE":
                // Center block shape for title to sit inside
                slide.addShape(pptx.ShapeType.rect, { x: 1, y: 1.5, w: 8, h: 2.5, fill: { color: isDark ? '0F172A' : 'EFF6FF' }, line: { color: accentColor, width: 2 } });

                // Title (Extracting _title or title just in case JSON variation)
                slide.addText(data._title || data.title, {
                    x: 1, y: 1.5, w: 8, h: 2.5,
                    fontSize: 44, bold: true, color: isDark ? 'FFFFFF' : '0F172A', align: "center", fontFace: "Helvetica Neue"
                });
                break;

            case "TWO_COLUMN":
                // Premium Corporate Sidebar (Darker color blocking)
                slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 3.5, h: "100%", fill: { color: isDark ? '0F172A' : '334155' } });

                // Left Column (Title sitting inside the sidebar)
                slide.addText(data.title, {
                    x: 0.4, y: 0.5, w: 2.7, h: 4,
                    fontSize: 36, bold: true, color: "FFFFFF", fontFace: "Helvetica Neue", align: "left"
                });

                // Right Column 1 (First list of bullets on main light/dark background)
                if (data.bullets_left && data.bullets_left.length > 0) {
                    slide.addText(data.bullets_left.join('\\n'), {
                        x: 4.0, y: 1.0, w: 5.5, h: 2.0,
                        fontSize: 20, color: textColor, bullet: { type: 'number' }, lineSpacing: 32, fontFace: "Helvetica"
                    });
                }

                // Right Column 2 (Second list of bullets)
                if (data.bullets_right && data.bullets_right.length > 0) {
                    slide.addText(data.bullets_right.join('\\n'), {
                        x: 4.0, y: 3.2, w: 5.5, h: 2.0,
                        fontSize: 20, color: textColor, bullet: { type: 'number', numberStartAt: (data.bullets_left?.length || 0) + 1 }, lineSpacing: 32, fontFace: "Helvetica"
                    });
                }
                break;

            case "BIG_STAT":
                // Standard Title
                slide.addText(data.title, { x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 32, bold: true, color: accentColor, fontFace: "Helvetica Neue" });

                // Background shape behind stat for visual pop
                slide.addShape(pptx.ShapeType.rect, { x: 0.5, y: 1.8, w: 9, h: 2, fill: { color: isDark ? '0F172A' : 'F1F5F9' } });

                if (data.stat) {
                    slide.addText(data.stat, { x: 0.5, y: 1.8, w: 9, h: 2, fontSize: 68, bold: true, color: accentColor, align: "center", fontFace: "Arial Black" });
                }

                if (data.bullets && data.bullets.length > 0) {
                    slide.addText(data.bullets.join('\\n'), {
                        x: 0.5, y: 4.0, w: 9, h: 1.0,
                        fontSize: 20, color: textColor, bullet: true, lineSpacing: 28, fontFace: "Helvetica"
                    });
                }
                break;

            case "STANDARD_BULLETS":
            default:
                slide.addText(data.title, { x: 0.5, y: 0.5, w: 9, h: 1, fontSize: 32, bold: true, color: accentColor, fontFace: "Helvetica Neue" });

                // Add a subtle line below the title
                slide.addShape(pptx.ShapeType.line, { x: 0.5, y: 1.3, w: 9, h: 0, line: { color: "CBD5E1", width: 1 } });

                if (data.bullets && data.bullets.length > 0) {
                    slide.addText(data.bullets.join('\\n'), {
                        x: 0.5, y: 1.8, w: 9, h: 3.5,
                        fontSize: 22, color: textColor, bullet: true, lineSpacing: 36, fontFace: "Helvetica"
                    });
                }
                break;
        }
    });

    pptx.writeFile({ fileName: `${filename.replace(/\\s+/g, '_')}.pptx` });
};
